config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :parties
  root :to => 'parties#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/party.rb
#
# Table Schema
# ------------
# id            - int(11)      - default NULL
# host_name     - varchar(255) - default NULL
# host_email    - varchar(255) - default NULL
# numgsts       - int(11)      - default NULL
# guest_names   - text         - default NULL
# venue         - varchar(255) - default NULL
# location      - varchar(255) - default NULL
# theme         - varchar(255) - default NULL
# when          - datetime     - default NULL
# when_its_over - datetime     - default NULL
# descript      - text         - default NULL
#
class Party < ApplicationRecord
  validates_length_of :host_name, :maximum => 255
  validates_length_of :host_email, :maximum => 255
  validates_length_of :venue, :maximum => 255
  validates_length_of :location, :maximum => 255
  validates_length_of :theme, :maximum => 255

  validate :validations

  def validations
    # if host_name.length<255 || host_email.length<255 || venue.length<255 || location.size<255 || theme.size<255
    #   errors.add(:base,"Input was too long.")
    # end
    # ruby doesn't like us using when as column name for some reason
    if self[:when]>when_its_over
      errors.add(:base,"Incorrect party time.")
    end
    if self.numgsts.nil?
      numgsts = 0
    end
    if venue.length > 0 && location.length < 0
      errors.add(:location,"Where is the party?")
    end
    if guest_names.split(',').size != self.numgsts
      errors.add(:guest_names,"Missing guest name")
    end
  end

  def after_save
    # clean "Harry S. Truman" guest name to "Harry S._Truman"
    # clean "Roger      Rabbit" guest name to "Roger Rabbit"
    gnames = []
    guest_names.split(',').each do |g|
      g.squeeze!
      names=g.split(' ')
      gnames << "#{names[0]} #{names[1..-1].join('_')}"
    end
    guest_names = gnames
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :set_party, only: [:show]

  def index
    @parties = Array.new

    if !params[:sort].blank?
      order = "#{params[:sort]} #{(params[:asc].blank? || params[:asc] == 'true') ? 'DESC' : 'ASC'}"
      Party.order(order).all.each do |party|
        @parties << party
      end
    else
      order = "parties.when #{(params[:asc].blank? || params[:asc] == 'true') ? 'DESC' : 'ASC'}"
      @parties = Party.order(order).all
    end
  end

  def new
    @party = Party.new
    # so the view shows 0 and not blank
    @party.numgsts = 0
  end

  def show
  end

  def create
    @party = Party.new
    if params[:party][:numgsts].blank?
      params[:party][:numgsts]=0
    end

    @party.attributes = party_params
    if @party.save
      # if end is blank, set to end of day
      if @party.when_its_over.blank?
        @party.when_its_over=@party.when.end_of_day
        @party.save
      end
      @party.after_save
      redirect_to root_path
    else
      flash[:notice]="Party was incorrect."
      redirect_to new_party_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    def party_params
      params.require(:party).permit(:host_name, :host_email, :numgsts, :guest_names, :venue, :location, :theme, :when, :when_its_over, :descript)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeExercise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parties/index.html.erb
<h1>Party List</h1>
<table>
  <tr>
    <td>Hosted By</td>
    <td>Host Email</td>
    <td># of Guests</td>
    <td>Guest Names</td>
    <td>Venue Name</td>
    <td>Venue Address</td>
    <td>Party Theme</td>
    <td>Party Start Time</td>
    <td>Party End Time</td>
    <td>Description</td>
  </tr>
  <tr>
    <td colspan="10"><%= link_to "New",new_parties_url %></td>
  </tr>
<% @parties.each do |party| %>
  <tr>
    <td>
      <%- if party.host_name.blank? %>
        No host was found
      <%- else %>
        <%= party.host_name %>
      <%- end %>
    </td>
    <td>
      <%= party.host_email %>
    </td>
    <td><%= party.numgsts %></td>
    <td>
      <%- party.guest_names.split(',').compact.each do |g| %>
        <%- f,l=g.split(' ') %>
        <%= l %>, <%= f %>
      <%- end %>
    </td>
    <td><%= party.venue %></td>
    <td><%= party.location %></td>
    <td class="time"><%= party.try(:when).strftime('%Y-%m-%d %I:%M:%S') %></td>
    <td class="time"><%= party.try(:when_its_over).strftime('%Y-%m-%d %I:%M:%S') %></td>
    <td><%= party.descript %></td>
  </tr>
<% end %>
</table>
<script type="javascript">
  $('.time').each(function() {$(this).value(moment($(this).value).format('MM/DD/YYYY h:mm a'));});
</script>

app/views/parties/new.html.erb
<h1>Add a Party</h1>
<%= form_for(@party) do |f| %>
    <div class="container">
    <div class="form-group">
  <label>Hosted By</label>
  <%= f.text_field(:host_name) %>
</div>
    <div class="form-group">
  <label>Host Email</label>
  <%= f.text_field(:host_email) %>
</div>
    <div class="form-group">
  <label>Number of Guests</label>
  <%= f.text_field(:numgsts) %>
</div>
    <div class="form-group">
  <label>Guest Names (separate by ',')</label>
  <%= f.text_area(:guest_names) %>
</div>
    <div class="form-group">
  <label>Venue Name</label>
  <%= f.text_field(:venue) %>
</div>
    <div class="form-group">
  <label>Venue Location</label>
  <%= f.text_field(:location) %>
</div>
    <div class="form-group">
  <label>Party Theme</label>
  <%= f.text_field(:theme) %>
</div>
    <div class="form-group">
  <label>Party Start Time</label>
  <%= f.datetime_select(:when) %>
</div>
    <div class="form-group">
  <label>Party End Time</label>
  <%= f.datetime_select(:when_its_over) %>
</div>
    <div class="form-group">
  <label>Description</label>
  <%= f.text_area(:descript) %>
</div>
  <%= f.submit %>
    </div>
<%- end %>

app/views/parties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @party.host_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @party.host_email %>
</p>

<p>
  <strong>No Guests:</strong>
  <%= @party.numgsts %>
</p>

<p>
  <strong>Guest Names:</strong>
  <%= @party.guest_names %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @party.venue %>
</p>

<p>
  <strong>Location:</strong>
  <%= @party.location %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @party.theme %>
</p>

<p>
  <strong>When:</strong>
  <%= @party.when %>
</p>

<p>
  <strong>When its over:</strong>
  <%= @party.when_its_over %>
</p>
<p>
  <strong>Desc:</strong>
  <%= @party.descript %>
</p>